before:
  hooks:
    - go mod download
builds:
  - binary: skuld
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

scoop:
  bucket:
    owner: DEEP-IMPACT-AG
    name: scoop-hyperdrive
  commit_author:
      name: codebuild
      email: info@deep-impact.ch
  homepage: "https://github.com/DEEP-IMPACT-AG/skuld"
  description: "CLI tool for AWS MFA credentials"
  license: Apache 2.0

brews:
  - tap:
      owner: DEEP-IMPACT-AG
      name: homebrew-hyperdrive
    commit_author:
      name: codebuild
      email: info@deep-impact.ch
    homepage: "https://github.com/DEEP-IMPACT-AG/skuld"
    description: "CLI tool for AWS MFA credentials"

      #snapcrafts:
      #  - summary: "CLI toon for AWS MFA credentials"
      #    description: "CLI toon for AWS MFA credentials"
      #    grade: devel
      #    confinement: classic
      #    publish: true
