version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/stanislas/grt
    steps:
      - checkout
      - run: ./build/build.sh
      - run: ./build/release.sh


workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /v.*/