version: 2
jobs:
  build:
    docker:
      - image: deepimpact/go-snapcraft-builder:1.0.3
    working_directory: /go/src/github.com/DEEP-IMPACT-AG/skuld
    steps:
      - checkout
      - run: ./build/build.sh
      - run: ./build/release.sh


workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /v.*/
