version: 2.1
workflows:
  main:
    jobs:
      - release:
          filters:
            tags:
              only: /v.*/
jobs:
  release:
    docker:
      - image: deepimpact/go-snapcraft-builder:1.0.3
    steps:
      - checkout
      - run: ./build/release.sh
